version: 2
jobs:
  publishImage:
    docker:
      - image: golang:1.11-alpine3.8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            apk add --update git make docker
            make release

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - publishImage
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
