version: 2
jobs:
  publishImage:
    docker:
      - image: golang:1.11-alpine3.8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            DOCKER_CLI_VERSION="18.09-ce"
            DOWNLOAD_URL="https://download.docker.com/linux/static/stable/x86_64/docker-$DOCKER_CLI_VERSION.tgz"

            # install docker client
            apk --update add curl \
              && mkdir -p /tmp/download \
              && curl -L $DOWNLOAD_URL | tar -xz -C /tmp/download \
              && mv /tmp/download/docker/docker /bin/

            apk add git make
            make release

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - publishImage
